### ISSUE TITLE
Overall function structure

### ISSUE THREAD

**Issue by LucasLev** [AbhiK002/Tasky#5]
Hey, following my comment on reddit I think there is some restructuration to be done in the way some core functions are organized. More precisely, I think that the "Functions" class : 

- should no longer be a class with self values, but instead functions with actual parameters or global variables (for example, the different paths could be global in my opinion, as they are needed pretty much everywhere), as we don't really use the object for anything else than its methods.
- should be in a specific module imported by tasky_gui and tasky_console, so it is easier to expand and to maintain

**Comment by AbhiK002** [comment]
Hi, reading your pointers I realized separating Functions into a common file which both files can import is a good idea and I will start working on this very soon. Learning something new everyday is pretty fun! Thanks a lot for your feedback, I really appreciate it.

**Comment by AbhiK002** [comment]
Sure!

**Comment by AbhiK002** [comment]
Due to some personal reasons, I couldn't spare much time for this although I will implement this later. Tasky v1.0.1, the latest release is a stable one, so no issues! Thank you.
